services:
  cine-magic-js:
    container_name: cine-magic-js
    build:
      context: ./
      dockerfile: Dockerfile
    image: cine-magic-js:latest
    networks:
      - alexkaralis-deploy_web
    restart: unless-stopped

networks:
  alexkaralis-deploy_web:
    external: true
