services:
  cine-magic-js:
    container_name: cine-magic-js
    build:
      context: ./
      dockerfile: Dockerfile
    image: cine-magic-js:latest
    ports:
      - "3001:80"
    networks:
      - cine-magic-js-net
    restart: unless-stopped

networks:
  cine-magic-js-net:
